In [1]:
%sql
CREATE TABLE Employees (
    emp_id INT,
    emp_name VARCHAR(50),
    department VARCHAR(50),
    salary INT,
    city VARCHAR(50),
    experience INT
);

Table Employees created successfully.

In [2]:
%sql
INSERT INTO Employees VALUES
(101, 'Rahul', 'IT', 75000, 'Hyderabad', 5),
(102, 'Anjali', 'HR', 45000, 'Chennai', 3),
(103, 'Kiran', 'IT', 82000, 'Bangalore', 6),
(104, 'Sneha', 'Finance', 67000, 'Hyderabad', 4),
(105, 'Aman', 'HR', 39000, 'Pune', 2),
(106, 'Ravi', 'Finance', 91000, 'Mumbai', 8),
(107, 'Divya', 'IT', 55000, 'Chennai', 3),
(108, 'Meena', 'Sales', 48000, 'Bangalore', 2),
(109, 'Arjun', 'Sales', 61000, 'Hyderabad', 5),
(110, 'Pooja', 'IT', 73000, 'Mumbai', 4),
(111, 'Vikas', 'HR', 52000, 'Pune', 3),
(112, 'Nisha', 'Finance', 88000, 'Bangalore', 7),
(113, 'Tarun', 'Sales', 46000, 'Chennai', 2),
(114, 'Kavya', 'IT', 97000, 'Hyderabad', 9),
(115, 'Manoj', 'Finance', 58000, 'Mumbai', 4);

15 rows inserted successfully.

*SELECT*

Display all employee details.

In [3]:
%sql
SELECT * FROM Employees;

 emp_id emp_name department  salary      city  experience
    101    Rahul         IT   75000 Hyderabad           5
    102   Anjali         HR   45000   Chennai           3
    103    Kiran         IT   82000 Bangalore           6
    104    Sneha    Finance   67000 Hyderabad           4
    105     Aman         HR   39000      Pune           2
    106     Ravi    Finance   91000    Mumbai           8
    107    Divya         IT   55000   Chennai           3
    108    Meena      Sales   48000 Bangalore           2
    109    Arjun      Sales   61000 Hyderabad           5
    110    Pooja         IT   73000    Mumbai           4
    111    Vikas         HR   52000      Pune           3
    112    Nisha    Finance   88000 Bangalore           7
    113    Tarun      Sales   46000   Chennai           2
    114    Kavya         IT   97000 Hyderabad           9
    115    Manoj    Finance   58000    Mumbai           4

Display only employee names and salaries.

In [4]:
%sql
SELECT emp_name, salary FROM Employees;

emp_name  salary
   Rahul   75000
  Anjali   45000
   Kiran   82000
   Sneha   67000
    Aman   39000
    Ravi   91000
   Divya   55000
   Meena   48000
   Arjun   61000
   Pooja   73000
   Vikas   52000
   Nisha   88000
   Tarun   46000
   Kavya   97000
   Manoj   58000

Display employee names and departments.

In [5]:
%sql
SELECT emp_name, department FROM Employees;

emp_name department
   Rahul         IT
  Anjali         HR
   Kiran         IT
   Sneha    Finance
    Aman         HR
    Ravi    Finance
   Divya         IT
   Meena      Sales
   Arjun      Sales
   Pooja         IT
   Vikas         HR
   Nisha    Finance
   Tarun      Sales
   Kavya         IT
   Manoj    Finance

Display all employees from the IT department.

In [6]:
%sql
SELECT * FROM Employees WHERE department = 'IT';

 emp_id emp_name department  salary      city  experience
    101    Rahul         IT   75000 Hyderabad           5
    103    Kiran         IT   82000 Bangalore           6
    107    Divya         IT   55000   Chennai           3
    110    Pooja         IT   73000    Mumbai           4
    114    Kavya         IT   97000 Hyderabad           9

Display employee names and experience.

In [7]:
%sql
SELECT emp_name, experience FROM Employees;

emp_name  experience
   Rahul           5
  Anjali           3
   Kiran           6
   Sneha           4
    Aman           2
    Ravi           8
   Divya           3
   Meena           2
   Arjun           5
   Pooja           4
   Vikas           3
   Nisha           7
   Tarun           2
   Kavya           9
   Manoj           4

*WHERE*

Find employees with salary greater than 70000.

In [8]:
%sql
SELECT * FROM Employees WHERE salary > 70000;

 emp_id emp_name department  salary      city  experience
    101    Rahul         IT   75000 Hyderabad           5
    103    Kiran         IT   82000 Bangalore           6
    106     Ravi    Finance   91000    Mumbai           8
    110    Pooja         IT   73000    Mumbai           4
    112    Nisha    Finance   88000 Bangalore           7
    114    Kavya         IT   97000 Hyderabad           9

Find employees working in Hyderabad.

In [9]:
%sql
SELECT * FROM Employees WHERE city = 'Hyderabad';

 emp_id emp_name department  salary      city  experience
    101    Rahul         IT   75000 Hyderabad           5
    104    Sneha    Finance   67000 Hyderabad           4
    109    Arjun      Sales   61000 Hyderabad           5
    114    Kavya         IT   97000 Hyderabad           9

Find employees with experience less than 4 years.

In [10]:
%sql
SELECT * FROM Employees WHERE experience < 4;

 emp_id emp_name department  salary      city  experience
    102   Anjali         HR   45000   Chennai           3
    105     Aman         HR   39000      Pune           2
    107    Divya         IT   55000   Chennai           3
    108    Meena      Sales   48000 Bangalore           2
    111    Vikas         HR   52000      Pune           3
    113    Tarun      Sales   46000   Chennai           2

Find employees from Finance department.

In [11]:
%sql
SELECT * FROM Employees WHERE department = 'Finance';

 emp_id emp_name department  salary      city  experience
    104    Sneha    Finance   67000 Hyderabad           4
    106     Ravi    Finance   91000    Mumbai           8
    112    Nisha    Finance   88000 Bangalore           7
    115    Manoj    Finance   58000    Mumbai           4

Find employees whose salary is equal to 52000.

In [12]:
%sql
SELECT * FROM Employees WHERE salary = 52000;

 emp_id emp_name department  salary city  experience
    111    Vikas         HR   52000 Pune           3

*GROUP BY*

Find total salary department-wise.

In [13]:
%sql
SELECT department, SUM(salary) as total_salary FROM Employees GROUP BY department;

department  total_salary
   Finance        304000
        HR        136000
        IT        382000
     Sales        155000

Find average salary in each department.

In [14]:
%sql
SELECT department, AVG(salary) as avg_salary FROM Employees GROUP BY department;

department   avg_salary
   Finance 76000.000000
        HR 45333.333333
        IT 76400.000000
     Sales 51666.666667

Count employees in each city.

In [15]:
%sql
SELECT city, COUNT(*) as employee_count FROM Employees GROUP BY city;

     city  employee_count
Bangalore               3
  Chennai               3
Hyderabad               4
   Mumbai               3
     Pune               2

Find maximum salary in each department.

In [16]:
%sql
SELECT department, MAX(salary) as max_salary FROM Employees GROUP BY department;

department  max_salary
   Finance       91000
        HR       52000
        IT       97000
     Sales       61000

Find minimum experience department-wise.

In [17]:
%sql
SELECT department, MIN(experience) as min_experience FROM Employees GROUP BY department;

department  min_experience
   Finance               4
        HR               2
        IT               3
     Sales               2

*HAVING*

Find departments having more than 3 employees.

In [18]:
%sql
SELECT department, COUNT(*) as num_employees FROM Employees GROUP BY department HAVING COUNT(*) > 3;

department  num_employees
   Finance              4
        IT              5

Find departments where average salary is greater than 60000.

In [19]:
%sql
SELECT department, AVG(salary) as avg_salary FROM Employees GROUP BY department HAVING AVG(salary) > 60000;

department  avg_salary
   Finance     76000.0
        IT     76400.0

Find cities having more than 2 employees.

In [20]:
%sql
SELECT city, COUNT(*) as num_employees FROM Employees GROUP BY city HAVING COUNT(*) > 2;

     city  num_employees
Bangalore              3
  Chennai              3
Hyderabad              4
   Mumbai              3

Find departments where total salary is greater than 200000.

In [21]:
%sql
SELECT department, SUM(salary) as total_salary FROM Employees GROUP BY department HAVING SUM(salary) > 200000;

department  total_salary
   Finance        304000
        IT        382000

Find departments where maximum salary is above 90000.

In [22]:
%sql
SELECT department, MAX(salary) as max_salary FROM Employees GROUP BY department HAVING MAX(salary) > 90000;

department  max_salary
   Finance       91000
        IT       97000

*TOP*

Display top 5 highest paid employees.

In [23]:
%sql
SELECT * FROM Employees ORDER BY salary DESC LIMIT 5;

 emp_id emp_name department  salary      city  experience
    114    Kavya         IT   97000 Hyderabad           9
    106     Ravi    Finance   91000    Mumbai           8
    112    Nisha    Finance   88000 Bangalore           7
    103    Kiran         IT   82000 Bangalore           6
    101    Rahul         IT   75000 Hyderabad           5

Display top 3 employees with highest experience.

In [24]:
%sql
SELECT * FROM Employees ORDER BY experience DESC LIMIT 3;

 emp_id emp_name department  salary      city  experience
    114    Kavya         IT   97000 Hyderabad           9
    106     Ravi    Finance   91000    Mumbai           8
    112    Nisha    Finance   88000 Bangalore           7

Display top 2 salaries from Finance department.

In [25]:
%sql
SELECT * FROM Employees WHERE department = 'Finance' ORDER BY salary DESC LIMIT 2;

 emp_id emp_name department  salary      city  experience
    106     Ravi    Finance   91000    Mumbai           8
    112    Nisha    Finance   88000 Bangalore           7

Display top 4 employees from Hyderabad.

In [26]:
%sql
SELECT * FROM Employees WHERE city = 'Hyderabad' ORDER BY salary DESC LIMIT 4;

 emp_id emp_name department  salary      city  experience
    114    Kavya         IT   97000 Hyderabad           9
    101    Rahul         IT   75000 Hyderabad           5
    104    Sneha    Finance   67000 Hyderabad           4
    109    Arjun      Sales   61000 Hyderabad           5

Display top 1 highest salary employee.

In [27]:
%sql
SELECT * FROM Employees ORDER BY salary DESC LIMIT 1;

 emp_id emp_name department  salary      city  experience
    114    Kavya         IT   97000 Hyderabad           9

*DISTINCT*

Display distinct department names.

In [28]:
%sql
SELECT DISTINCT department FROM Employees;

department
        IT
        HR
   Finance
     Sales

Display distinct city names.

In [29]:
%sql
SELECT DISTINCT city FROM Employees;

     city
Hyderabad
  Chennai
Bangalore
     Pune
   Mumbai

Display distinct salary values.

In [30]:
%sql
SELECT DISTINCT salary FROM Employees;

 salary
  75000
  45000
  82000
  67000
  39000
  91000
  55000
  48000
  61000
  73000
  52000
  88000
  46000
  97000
  58000

Display distinct combinations of department and city.

In [31]:
%sql
SELECT DISTINCT department, city FROM Employees;

department      city
        IT Hyderabad
        HR   Chennai
        IT Bangalore
   Finance Hyderabad
        HR      Pune
   Finance    Mumbai
        IT   Chennai
     Sales Bangalore
     Sales Hyderabad
        IT    Mumbai
   Finance Bangalore
     Sales   Chennai

Display distinct experience values.

In [32]:
%sql
SELECT DISTINCT experience FROM Employees;

 experience
          5
          3
          6
          4
          2
          8
          7
          9

*COMPARISON OPERATORS*

Find employees with salary >= 80000.

In [33]:
%sql
SELECT * FROM Employees WHERE salary >= 80000;

 emp_id emp_name department  salary      city  experience
    103    Kiran         IT   82000 Bangalore           6
    106     Ravi    Finance   91000    Mumbai           8
    112    Nisha    Finance   88000 Bangalore           7
    114    Kavya         IT   97000 Hyderabad           9

Find employees with experience <= 3.

In [34]:
%sql
SELECT * FROM Employees WHERE experience <= 3;

 emp_id emp_name department  salary      city  experience
    102   Anjali         HR   45000   Chennai           3
    105     Aman         HR   39000      Pune           2
    107    Divya         IT   55000   Chennai           3
    108    Meena      Sales   48000 Bangalore           2
    111    Vikas         HR   52000      Pune           3
    113    Tarun      Sales   46000   Chennai           2

Find employees whose salary <> 45000.

In [35]:
%sql
SELECT * FROM Employees WHERE salary <> 45000;

 emp_id emp_name department  salary      city  experience
    101    Rahul         IT   75000 Hyderabad           5
    103    Kiran         IT   82000 Bangalore           6
    104    Sneha    Finance   67000 Hyderabad           4
    105     Aman         HR   39000      Pune           2
    106     Ravi    Finance   91000    Mumbai           8
    107    Divya         IT   55000   Chennai           3
    108    Meena      Sales   48000 Bangalore           2
    109    Arjun      Sales   61000 Hyderabad           5
    110    Pooja         IT   73000    Mumbai           4
    111    Vikas         HR   52000      Pune           3
    112    Nisha    Finance   88000 Bangalore           7
    113    Tarun      Sales   46000   Chennai           2
    114    Kavya         IT   97000 Hyderabad           9
    115    Manoj    Finance   58000    Mumbai           4

Find employees with salary < 50000.

In [36]:
%sql
SELECT * FROM Employees WHERE salary < 50000;

 emp_id emp_name department  salary      city  experience
    102   Anjali         HR   45000   Chennai           3
    105     Aman         HR   39000      Pune           2
    108    Meena      Sales   48000 Bangalore           2
    113    Tarun      Sales   46000   Chennai           2

Find employees with experience > 5.

In [37]:
%sql
SELECT * FROM Employees WHERE experience > 5;

 emp_id emp_name department  salary      city  experience
    103    Kiran         IT   82000 Bangalore           6
    106     Ravi    Finance   91000    Mumbai           8
    112    Nisha    Finance   88000 Bangalore           7
    114    Kavya         IT   97000 Hyderabad           9

*LOGICAL OPERATORS*

Find employees from IT department AND salary greater than 70000.

In [38]:
%sql
SELECT * FROM Employees WHERE department = 'IT' AND salary > 70000;

 emp_id emp_name department  salary      city  experience
    101    Rahul         IT   75000 Hyderabad           5
    103    Kiran         IT   82000 Bangalore           6
    110    Pooja         IT   73000    Mumbai           4
    114    Kavya         IT   97000 Hyderabad           9

Find employees from Hyderabad OR Bangalore.

In [39]:
%sql
SELECT * FROM Employees WHERE city = 'Hyderabad' OR city = 'Bangalore';

 emp_id emp_name department  salary      city  experience
    101    Rahul         IT   75000 Hyderabad           5
    103    Kiran         IT   82000 Bangalore           6
    104    Sneha    Finance   67000 Hyderabad           4
    108    Meena      Sales   48000 Bangalore           2
    109    Arjun      Sales   61000 Hyderabad           5
    112    Nisha    Finance   88000 Bangalore           7
    114    Kavya         IT   97000 Hyderabad           9

Find employees from HR department AND experience less than 3.

In [40]:
%sql
SELECT * FROM Employees WHERE department = 'HR' AND experience < 3;

 emp_id emp_name department  salary city  experience
    105     Aman         HR   39000 Pune           2

Find employees with salary greater than 60000 OR experience greater than 6.

In [41]:
%sql
SELECT * FROM Employees WHERE salary > 60000 OR experience > 6;

 emp_id emp_name department  salary      city  experience
    101    Rahul         IT   75000 Hyderabad           5
    103    Kiran         IT   82000 Bangalore           6
    104    Sneha    Finance   67000 Hyderabad           4
    106     Ravi    Finance   91000    Mumbai           8
    109    Arjun      Sales   61000 Hyderabad           5
    110    Pooja         IT   73000    Mumbai           4
    112    Nisha    Finance   88000 Bangalore           7
    114    Kavya         IT   97000 Hyderabad           9

Find employees NOT from Sales department.

In [42]:
%sql
SELECT * FROM Employees WHERE department != 'Sales';

 emp_id emp_name department  salary      city  experience
    101    Rahul         IT   75000 Hyderabad           5
    102   Anjali         HR   45000   Chennai           3
    103    Kiran         IT   82000 Bangalore           6
    104    Sneha    Finance   67000 Hyderabad           4
    105     Aman         HR   39000      Pune           2
    106     Ravi    Finance   91000    Mumbai           8
    107    Divya         IT   55000   Chennai           3
    110    Pooja         IT   73000    Mumbai           4
    111    Vikas         HR   52000      Pune           3
    112    Nisha    Finance   88000 Bangalore           7
    114    Kavya         IT   97000 Hyderabad           9
    115    Manoj    Finance   58000    Mumbai           4

*IN AND NOT IN*

Find employees working in ('Hyderabad', 'Mumbai').

In [43]:
%sql
SELECT * FROM Employees WHERE city IN ('Hyderabad', 'Mumbai');

 emp_id emp_name department  salary      city  experience
    101    Rahul         IT   75000 Hyderabad           5
    104    Sneha    Finance   67000 Hyderabad           4
    106     Ravi    Finance   91000    Mumbai           8
    109    Arjun      Sales   61000 Hyderabad           5
    110    Pooja         IT   73000    Mumbai           4
    114    Kavya         IT   97000 Hyderabad           9
    115    Manoj    Finance   58000    Mumbai           4

Find employees whose department IN ('IT', 'Finance').

In [44]:
%sql
SELECT * FROM Employees WHERE department IN ('IT', 'Finance');

 emp_id emp_name department  salary      city  experience
    101    Rahul         IT   75000 Hyderabad           5
    103    Kiran         IT   82000 Bangalore           6
    104    Sneha    Finance   67000 Hyderabad           4
    106     Ravi    Finance   91000    Mumbai           8
    107    Divya         IT   55000   Chennai           3
    110    Pooja         IT   73000    Mumbai           4
    112    Nisha    Finance   88000 Bangalore           7
    114    Kavya         IT   97000 Hyderabad           9
    115    Manoj    Finance   58000    Mumbai           4

Find employees whose city NOT IN ('Chennai', 'Pune').

In [45]:
%sql
SELECT * FROM Employees WHERE city NOT IN ('Chennai', 'Pune');

 emp_id emp_name department  salary      city  experience
    101    Rahul         IT   75000 Hyderabad           5
    103    Kiran         IT   82000 Bangalore           6
    104    Sneha    Finance   67000 Hyderabad           4
    106     Ravi    Finance   91000    Mumbai           8
    108    Meena      Sales   48000 Bangalore           2
    109    Arjun      Sales   61000 Hyderabad           5
    110    Pooja         IT   73000    Mumbai           4
    112    Nisha    Finance   88000 Bangalore           7
    114    Kavya         IT   97000 Hyderabad           9
    115    Manoj    Finance   58000    Mumbai           4

Find employees whose salary IN (45000, 75000, 91000).

In [46]:
%sql
SELECT * FROM Employees WHERE salary IN (45000, 75000, 91000);

 emp_id emp_name department  salary      city  experience
    101    Rahul         IT   75000 Hyderabad           5
    102   Anjali         HR   45000   Chennai           3
    106     Ravi    Finance   91000    Mumbai           8

Find employees whose department NOT IN ('HR', 'Sales').

In [47]:
%sql
SELECT * FROM Employees WHERE department NOT IN ('HR', 'Sales');

 emp_id emp_name department  salary      city  experience
    101    Rahul         IT   75000 Hyderabad           5
    103    Kiran         IT   82000 Bangalore           6
    104    Sneha    Finance   67000 Hyderabad           4
    106     Ravi    Finance   91000    Mumbai           8
    107    Divya         IT   55000   Chennai           3
    110    Pooja         IT   73000    Mumbai           4
    112    Nisha    Finance   88000 Bangalore           7
    114    Kavya         IT   97000 Hyderabad           9
    115    Manoj    Finance   58000    Mumbai           4

*BETWEEN*

Find employees with salary BETWEEN 50000 AND 80000.

In [48]:
%sql
SELECT * FROM Employees WHERE salary BETWEEN 50000 AND 80000;

 emp_id emp_name department  salary      city  experience
    101    Rahul         IT   75000 Hyderabad           5
    104    Sneha    Finance   67000 Hyderabad           4
    107    Divya         IT   55000   Chennai           3
    109    Arjun      Sales   61000 Hyderabad           5
    110    Pooja         IT   73000    Mumbai           4
    111    Vikas         HR   52000      Pune           3
    115    Manoj    Finance   58000    Mumbai           4

Find employees with experience BETWEEN 3 AND 6.

In [49]:
%sql
SELECT * FROM Employees WHERE experience BETWEEN 3 AND 6;

 emp_id emp_name department  salary      city  experience
    101    Rahul         IT   75000 Hyderabad           5
    102   Anjali         HR   45000   Chennai           3
    103    Kiran         IT   82000 Bangalore           6
    104    Sneha    Finance   67000 Hyderabad           4
    107    Divya         IT   55000   Chennai           3
    109    Arjun      Sales   61000 Hyderabad           5
    110    Pooja         IT   73000    Mumbai           4
    111    Vikas         HR   52000      Pune           3
    115    Manoj    Finance   58000    Mumbai           4

Find employees whose emp_id BETWEEN 105 AND 112.

In [50]:
%sql
SELECT * FROM Employees WHERE emp_id BETWEEN 105 AND 112;

 emp_id emp_name department  salary      city  experience
    105     Aman         HR   39000      Pune           2
    106     Ravi    Finance   91000    Mumbai           8
    107    Divya         IT   55000   Chennai           3
    108    Meena      Sales   48000 Bangalore           2
    109    Arjun      Sales   61000 Hyderabad           5
    110    Pooja         IT   73000    Mumbai           4
    111    Vikas         HR   52000      Pune           3
    112    Nisha    Finance   88000 Bangalore           7

Find employees with salary NOT BETWEEN 40000 AND 60000.

In [51]:
%sql
SELECT * FROM Employees WHERE salary NOT BETWEEN 40000 AND 60000;

 emp_id emp_name department  salary      city  experience
    101    Rahul         IT   75000 Hyderabad           5
    103    Kiran         IT   82000 Bangalore           6
    104    Sneha    Finance   67000 Hyderabad           4
    105     Aman         HR   39000      Pune           2
    106     Ravi    Finance   91000    Mumbai           8
    109    Arjun      Sales   61000 Hyderabad           5
    110    Pooja         IT   73000    Mumbai           4
    112    Nisha    Finance   88000 Bangalore           7
    114    Kavya         IT   97000 Hyderabad           9

Find employees with experience BETWEEN 2 AND 4.

In [52]:
%sql
SELECT * FROM Employees WHERE experience BETWEEN 2 AND 4;

 emp_id emp_name department  salary      city  experience
    102   Anjali         HR   45000   Chennai           3
    104    Sneha    Finance   67000 Hyderabad           4
    105     Aman         HR   39000      Pune           2
    107    Divya         IT   55000   Chennai           3
    108    Meena      Sales   48000 Bangalore           2
    110    Pooja         IT   73000    Mumbai           4
    111    Vikas         HR   52000      Pune           3
    113    Tarun      Sales   46000   Chennai           2
    115    Manoj    Finance   58000    Mumbai           4

*LIKE OPERATOR*

Find employees whose names start with 'R'.

In [53]:
%sql
SELECT * FROM Employees WHERE emp_name LIKE 'R%';

 emp_id emp_name department  salary      city  experience
    101    Rahul         IT   75000 Hyderabad           5
    106     Ravi    Finance   91000    Mumbai           8

Find employees whose names end with 'a'.

In [54]:
%sql
SELECT * FROM Employees WHERE emp_name LIKE '%a';

 emp_id emp_name department  salary      city  experience
    104    Sneha    Finance   67000 Hyderabad           4
    107    Divya         IT   55000   Chennai           3
    108    Meena      Sales   48000 Bangalore           2
    110    Pooja         IT   73000    Mumbai           4
    112    Nisha    Finance   88000 Bangalore           7
    114    Kavya         IT   97000 Hyderabad           9

Find employees whose names contain 'v'.

In [55]:
%sql
SELECT * FROM Employees WHERE emp_name LIKE '%v%';

 emp_id emp_name department  salary      city  experience
    106     Ravi    Finance   91000    Mumbai           8
    107    Divya         IT   55000   Chennai           3
    111    Vikas         HR   52000      Pune           3
    114    Kavya         IT   97000 Hyderabad           9

Find employees whose city starts with 'B'.

In [56]:
%sql
SELECT * FROM Employees WHERE city LIKE 'B%';

 emp_id emp_name department  salary      city  experience
    103    Kiran         IT   82000 Bangalore           6
    108    Meena      Sales   48000 Bangalore           2
    112    Nisha    Finance   88000 Bangalore           7

Find employees whose department ends with 's'.

In [57]:
%sql
SELECT * FROM Employees WHERE department LIKE '%s';

 emp_id emp_name department  salary      city  experience
    108    Meena      Sales   48000 Bangalore           2
    109    Arjun      Sales   61000 Hyderabad           5
    113    Tarun      Sales   46000   Chennai           2