In [1]:
%sql
CREATE TABLE Students (
    student_id INT PRIMARY KEY,
    student_name VARCHAR(50),
    department VARCHAR(20),
    city VARCHAR(30),
    marks DECIMAL(5,2),
    attendance INT
);

Table Students created successfully.

In [2]:
%sql
INSERT INTO Students
(student_id, student_name, department, city, marks, attendance)
VALUES
(101,'Rahul','CS','Hyderabad',178,95),
(102,'Anjali','IT','Bangalore',165,88),
(103,'Kiran','CS','Chennai',150,91),
(104,'Sneha','ECE','Hyderabad',140,82),
(105,'Arjun','MECH','Pune',120,78),
(106,'Priya','IT','Hyderabad',190,97),
(107,'Vikram','CS','Bangalore',NULL,84),
(108,'Neha','ECE','Chennai',155,89),
(109,'Rohit','MECH','Hyderabad',98,65),
(110,'Pooja','IT','Pune',175,92),
(111,'Suresh','CS','Chennai',162,87),
(112,'Deepa','ECE','Bangalore',145,90),
(113,'Ajay','MECH','Hyderabad',130,73),
(114,'Kavya','CS','Pune',185,96),
(115,'Manoj','IT','Chennai',170,94),
(116,'Divya','ECE','Hyderabad',NULL,80),
(117,'Nikhil','MECH','Bangalore',158,86),
(118,'Swathi','CS','Hyderabad',148,88),
(119,'Harsha','IT','Pune',110,72),
(120,'Keerthi','ECE','Chennai',182,99);

20 rows inserted successfully.

🟢 Section A: Basic Level (5 Questions)

1️⃣ Display the first 5 rows of the dataset.

In [3]:
%sql
SELECT * FROM Students LIMIT 5;

 student_id student_name department      city  marks  attendance
        101        Rahul         CS Hyderabad    178          95
        102       Anjali         IT Bangalore    165          88
        103        Kiran         CS   Chennai    150          91
        104        Sneha        ECE Hyderabad    140          82
        105        Arjun       MECH      Pune    120          78

2️⃣ Check the total number of rows and columns in the dataset.

In [4]:
%sql
SELECT (SELECT COUNT(*) FROM Students) AS total_rows, 6 AS total_columns;

 total_rows  total_columns
         20              6

3️⃣ Find the number of missing values in each column.

In [5]:
%sql
SELECT 
  SUM(CASE WHEN student_id IS NULL THEN 1 ELSE 0 END) as missing_id,
  SUM(CASE WHEN student_name IS NULL THEN 1 ELSE 0 END) as missing_name,
  SUM(CASE WHEN department IS NULL THEN 1 ELSE 0 END) as missing_dept,
  SUM(CASE WHEN city IS NULL THEN 1 ELSE 0 END) as missing_city,
  SUM(CASE WHEN marks IS NULL THEN 1 ELSE 0 END) as missing_marks,
  SUM(CASE WHEN attendance IS NULL THEN 1 ELSE 0 END) as missing_attendance
FROM Students;

 missing_id  missing_name  missing_dept  missing_city  missing_marks  missing_attendance
          0             0             0             0              2                   0

4️⃣ Replace missing values in the marks column with the average marks.

In [6]:
%sql
WITH AvgMarks AS (SELECT AVG(marks) as avg_m FROM Students WHERE marks IS NOT NULL)
SELECT student_id, student_name, department, city, 
       COALESCE(marks, (SELECT avg_m FROM AvgMarks)) as marks, 
       attendance
FROM Students;

 student_id student_name department      city      marks  attendance
        101        Rahul         CS Hyderabad 178.000000          95
        102       Anjali         IT Bangalore 165.000000          88
        103        Kiran         CS   Chennai 150.000000          91
        104        Sneha        ECE Hyderabad 140.000000          82
        105        Arjun       MECH      Pune 120.000000          78
        106        Priya         IT Hyderabad 190.000000          97
        107       Vikram         CS Bangalore 153.388889          84
        108         Neha        ECE   Chennai 155.000000          89
        109        Rohit       MECH Hyderabad  98.000000          65
        110        Pooja         IT      Pune 175.000000          92
        111       Suresh         CS   Chennai 162.000000          87
        112        Deepa        ECE Bangalore 145.000000          90
        113         Ajay       MECH Hyderabad 130.000000          73
        114        Kavya         CS      Pune 185.000000          96
        115        Manoj         IT   Chennai 170.000000          94
        116        Divya        ECE Hyderabad 153.388889          80
        117       Nikhil       MECH Bangalore 158.000000          86
        118       Swathi         CS Hyderabad 148.000000          88
        119       Harsha         IT      Pune 110.000000          72
        120      Keerthi        ECE   Chennai 182.000000          99

5️⃣ Display only the name and marks columns.

In [7]:
%sql
SELECT student_name, marks FROM Students;

student_name  marks
       Rahul  178.0
      Anjali  165.0
       Kiran  150.0
       Sneha  140.0
       Arjun  120.0
       Priya  190.0
      Vikram    NaN
        Neha  155.0
       Rohit   98.0
       Pooja  175.0
      Suresh  162.0
       Deepa  145.0
        Ajay  130.0
       Kavya  185.0
       Manoj  170.0
       Divya    NaN
      Nikhil  158.0
      Swathi  148.0
      Harsha  110.0
     Keerthi  182.0

🟡 Section B: Filtering & Sorting (5 Questions)

6️⃣ Display students who scored more than 160 marks.

In [8]:
%sql
SELECT * FROM Students WHERE marks > 160;

 student_id student_name department      city  marks  attendance
        101        Rahul         CS Hyderabad    178          95
        102       Anjali         IT Bangalore    165          88
        106        Priya         IT Hyderabad    190          97
        110        Pooja         IT      Pune    175          92
        111       Suresh         CS   Chennai    162          87
        114        Kavya         CS      Pune    185          96
        115        Manoj         IT   Chennai    170          94
        120      Keerthi        ECE   Chennai    182          99

7️⃣ Display students from the "CS" department.

In [9]:
%sql
SELECT * FROM Students WHERE department = 'CS';

 student_id student_name department      city  marks  attendance
        101        Rahul         CS Hyderabad  178.0          95
        103        Kiran         CS   Chennai  150.0          91
        107       Vikram         CS Bangalore    NaN          84
        111       Suresh         CS   Chennai  162.0          87
        114        Kavya         CS      Pune  185.0          96
        118       Swathi         CS Hyderabad  148.0          88

8️⃣ Show students who have attendance greater than 85 and marks greater than 150.

In [10]:
%sql
SELECT * FROM Students WHERE attendance > 85 AND marks > 150;

 student_id student_name department      city  marks  attendance
        101        Rahul         CS Hyderabad    178          95
        102       Anjali         IT Bangalore    165          88
        106        Priya         IT Hyderabad    190          97
        108         Neha        ECE   Chennai    155          89
        110        Pooja         IT      Pune    175          92
        111       Suresh         CS   Chennai    162          87
        114        Kavya         CS      Pune    185          96
        115        Manoj         IT   Chennai    170          94
        117       Nikhil       MECH Bangalore    158          86
        120      Keerthi        ECE   Chennai    182          99

9️⃣ Sort the dataset by marks in descending order.

In [11]:
%sql
SELECT * FROM Students ORDER BY marks DESC;

 student_id student_name department      city  marks  attendance
        106        Priya         IT Hyderabad  190.0          97
        114        Kavya         CS      Pune  185.0          96
        120      Keerthi        ECE   Chennai  182.0          99
        101        Rahul         CS Hyderabad  178.0          95
        110        Pooja         IT      Pune  175.0          92
        115        Manoj         IT   Chennai  170.0          94
        102       Anjali         IT Bangalore  165.0          88
        111       Suresh         CS   Chennai  162.0          87
        117       Nikhil       MECH Bangalore  158.0          86
        108         Neha        ECE   Chennai  155.0          89
        103        Kiran         CS   Chennai  150.0          91
        118       Swathi         CS Hyderabad  148.0          88
        112        Deepa        ECE Bangalore  145.0          90
        104        Sneha        ECE Hyderabad  140.0          82
        113         Ajay       MECH Hyderabad  130.0          73
        105        Arjun       MECH      Pune  120.0          78
        119       Harsha         IT      Pune  110.0          72
        109        Rohit       MECH Hyderabad   98.0          65
        107       Vikram         CS Bangalore    NaN          84
        116        Divya        ECE Hyderabad    NaN          80

🔟 Display the top 3 students based on marks.

In [12]:
%sql
SELECT * FROM Students ORDER BY marks DESC LIMIT 3;

 student_id student_name department      city  marks  attendance
        106        Priya         IT Hyderabad    190          97
        114        Kavya         CS      Pune    185          96
        120      Keerthi        ECE   Chennai    182          99

🟠 Section C: Column Transformations (5 Questions)

1️⃣1️⃣ Create a new column percentage assuming total marks are 200.

In [13]:
%sql
SELECT *, (marks / 200.0) * 100 AS percentage FROM Students;

 student_id student_name department      city  marks  attendance  percentage
        101        Rahul         CS Hyderabad  178.0          95        89.0
        102       Anjali         IT Bangalore  165.0          88        82.5
        103        Kiran         CS   Chennai  150.0          91        75.0
        104        Sneha        ECE Hyderabad  140.0          82        70.0
        105        Arjun       MECH      Pune  120.0          78        60.0
        106        Priya         IT Hyderabad  190.0          97        95.0
        107       Vikram         CS Bangalore    NaN          84         NaN
        108         Neha        ECE   Chennai  155.0          89        77.5
        109        Rohit       MECH Hyderabad   98.0          65        49.0
        110        Pooja         IT      Pune  175.0          92        87.5
        111       Suresh         CS   Chennai  162.0          87        81.0
        112        Deepa        ECE Bangalore  145.0          90        72.5
        113         Ajay       MECH Hyderabad  130.0          73        65.0
        114        Kavya         CS      Pune  185.0          96        92.5
        115        Manoj         IT   Chennai  170.0          94        85.0
        116        Divya        ECE Hyderabad    NaN          80         NaN
        117       Nikhil       MECH Bangalore  158.0          86        79.0
        118       Swathi         CS Hyderabad  148.0          88        74.0
        119       Harsha         IT      Pune  110.0          72        55.0
        120      Keerthi        ECE   Chennai  182.0          99        91.0

1️⃣2️⃣ Create a new column grade using:
• A → percentage ≥ 85
• B → percentage ≥ 70
• C → percentage ≥ 50
• Fail → otherwise

In [14]:
%sql
WITH Pct AS (SELECT *, (marks / 200.0) * 100 AS percentage FROM Students)
SELECT *,
  CASE 
    WHEN percentage >= 85 THEN 'A'
    WHEN percentage >= 70 THEN 'B'
    WHEN percentage >= 50 THEN 'C'
    ELSE 'Fail'
  END AS grade
FROM Pct;

 student_id student_name department      city  marks  attendance  percentage grade
        101        Rahul         CS Hyderabad  178.0          95        89.0     A
        102       Anjali         IT Bangalore  165.0          88        82.5     B
        103        Kiran         CS   Chennai  150.0          91        75.0     B
        104        Sneha        ECE Hyderabad  140.0          82        70.0     B
        105        Arjun       MECH      Pune  120.0          78        60.0     C
        106        Priya         IT Hyderabad  190.0          97        95.0     A
        107       Vikram         CS Bangalore    NaN          84         NaN  Fail
        108         Neha        ECE   Chennai  155.0          89        77.5     B
        109        Rohit       MECH Hyderabad   98.0          65        49.0  Fail
        110        Pooja         IT      Pune  175.0          92        87.5     A
        111       Suresh         CS   Chennai  162.0          87        81.0     B
        112        Deepa        ECE Bangalore  145.0          90        72.5     B
        113         Ajay       MECH Hyderabad  130.0          73        65.0     C
        114        Kavya         CS      Pune  185.0          96        92.5     A
        115        Manoj         IT   Chennai  170.0          94        85.0     A
        116        Divya        ECE Hyderabad    NaN          80         NaN  Fail
        117       Nikhil       MECH Bangalore  158.0          86        79.0     B
        118       Swathi         CS Hyderabad  148.0          88        74.0     B
        119       Harsha         IT      Pune  110.0          72        55.0     C
        120      Keerthi        ECE   Chennai  182.0          99        91.0     A

1️⃣3️⃣ Add 5 bonus marks to every student.

In [15]:
%sql
SELECT *, marks + 5 AS bonus_marks FROM Students;

 student_id student_name department      city  marks  attendance  bonus_marks
        101        Rahul         CS Hyderabad  178.0          95        183.0
        102       Anjali         IT Bangalore  165.0          88        170.0
        103        Kiran         CS   Chennai  150.0          91        155.0
        104        Sneha        ECE Hyderabad  140.0          82        145.0
        105        Arjun       MECH      Pune  120.0          78        125.0
        106        Priya         IT Hyderabad  190.0          97        195.0
        107       Vikram         CS Bangalore    NaN          84          NaN
        108         Neha        ECE   Chennai  155.0          89        160.0
        109        Rohit       MECH Hyderabad   98.0          65        103.0
        110        Pooja         IT      Pune  175.0          92        180.0
        111       Suresh         CS   Chennai  162.0          87        167.0
        112        Deepa        ECE Bangalore  145.0          90        150.0
        113         Ajay       MECH Hyderabad  130.0          73        135.0
        114        Kavya         CS      Pune  185.0          96        190.0
        115        Manoj         IT   Chennai  170.0          94        175.0
        116        Divya        ECE Hyderabad    NaN          80          NaN
        117       Nikhil       MECH Bangalore  158.0          86        163.0
        118       Swathi         CS Hyderabad  148.0          88        153.0
        119       Harsha         IT      Pune  110.0          72        115.0
        120      Keerthi        ECE   Chennai  182.0          99        187.0

1️⃣4️⃣ Create a new column result where:
• Pass → percentage ≥ 40
• Fail → otherwise

In [16]:
%sql
WITH Pct AS (SELECT *, (marks / 200.0) * 100 AS percentage FROM Students)
SELECT *,
  CASE WHEN percentage >= 40 THEN 'Pass' ELSE 'Fail' END AS result
FROM Pct;

 student_id student_name department      city  marks  attendance  percentage result
        101        Rahul         CS Hyderabad  178.0          95        89.0   Pass
        102       Anjali         IT Bangalore  165.0          88        82.5   Pass
        103        Kiran         CS   Chennai  150.0          91        75.0   Pass
        104        Sneha        ECE Hyderabad  140.0          82        70.0   Pass
        105        Arjun       MECH      Pune  120.0          78        60.0   Pass
        106        Priya         IT Hyderabad  190.0          97        95.0   Pass
        107       Vikram         CS Bangalore    NaN          84         NaN   Fail
        108         Neha        ECE   Chennai  155.0          89        77.5   Pass
        109        Rohit       MECH Hyderabad   98.0          65        49.0   Pass
        110        Pooja         IT      Pune  175.0          92        87.5   Pass
        111       Suresh         CS   Chennai  162.0          87        81.0   Pass
        112        Deepa        ECE Bangalore  145.0          90        72.5   Pass
        113         Ajay       MECH Hyderabad  130.0          73        65.0   Pass
        114        Kavya         CS      Pune  185.0          96        92.5   Pass
        115        Manoj         IT   Chennai  170.0          94        85.0   Pass
        116        Divya        ECE Hyderabad    NaN          80         NaN   Fail
        117       Nikhil       MECH Bangalore  158.0          86        79.0   Pass
        118       Swathi         CS Hyderabad  148.0          88        74.0   Pass
        119       Harsha         IT      Pune  110.0          72        55.0   Pass
        120      Keerthi        ECE   Chennai  182.0          99        91.0   Pass

1️⃣5️⃣ Convert all student names to uppercase.

In [17]:
%sql
SELECT *, UPPER(student_name) AS student_name_upper FROM Students;

 student_id student_name department      city  marks  attendance student_name_upper
        101        Rahul         CS Hyderabad  178.0          95              RAHUL
        102       Anjali         IT Bangalore  165.0          88             ANJALI
        103        Kiran         CS   Chennai  150.0          91              KIRAN
        104        Sneha        ECE Hyderabad  140.0          82              SNEHA
        105        Arjun       MECH      Pune  120.0          78              ARJUN
        106        Priya         IT Hyderabad  190.0          97              PRIYA
        107       Vikram         CS Bangalore    NaN          84             VIKRAM
        108         Neha        ECE   Chennai  155.0          89               NEHA
        109        Rohit       MECH Hyderabad   98.0          65              ROHIT
        110        Pooja         IT      Pune  175.0          92              POOJA
        111       Suresh         CS   Chennai  162.0          87             SURESH
        112        Deepa        ECE Bangalore  145.0          90              DEEPA
        113         Ajay       MECH Hyderabad  130.0          73               AJAY
        114        Kavya         CS      Pune  185.0          96              KAVYA
        115        Manoj         IT   Chennai  170.0          94              MANOJ
        116        Divya        ECE Hyderabad    NaN          80              DIVYA
        117       Nikhil       MECH Bangalore  158.0          86             NIKHIL
        118       Swathi         CS Hyderabad  148.0          88             SWATHI
        119       Harsha         IT      Pune  110.0          72             HARSHA
        120      Keerthi        ECE   Chennai  182.0          99            KEERTHI

🔵 Section D: GroupBy & Aggregation (5 Questions)

1️⃣6️⃣ Find the average marks of each department.

In [18]:
%sql
SELECT department, AVG(marks) as avg_marks FROM Students GROUP BY department;

department  avg_marks
        CS      164.6
       ECE      155.5
        IT      162.0
      MECH      126.5

1️⃣7️⃣ Find the maximum marks scored in each city.

In [19]:
%sql
SELECT city, MAX(marks) as max_marks FROM Students GROUP BY city;

     city  max_marks
Bangalore        165
  Chennai        182
Hyderabad        190
     Pune        185

1️⃣8️⃣ Count the number of students in each department.

In [20]:
%sql
SELECT department, COUNT(*) as student_count FROM Students GROUP BY department;

department  student_count
        CS              6
       ECE              5
        IT              5
      MECH              4

1️⃣9️⃣ Find the department with the highest average marks.

In [21]:
%sql
SELECT department, AVG(marks) as avg_marks FROM Students GROUP BY department ORDER BY avg_marks DESC LIMIT 1;

department  avg_marks
        CS      164.6

2️⃣0️⃣ Create a pivot table showing average marks by department and city.

In [22]:
%sql
SELECT department,
  AVG(CASE WHEN city = 'Hyderabad' THEN marks END) as Hyderabad,
  AVG(CASE WHEN city = 'Bangalore' THEN marks END) as Bangalore,
  AVG(CASE WHEN city = 'Chennai' THEN marks END) as Chennai,
  AVG(CASE WHEN city = 'Pune' THEN marks END) as Pune
FROM Students GROUP BY department;

department  Hyderabad  Bangalore  Chennai  Pune
        CS      163.0        NaN    156.0 185.0
       ECE      140.0      145.0    168.5   NaN
        IT      190.0      165.0    170.0 142.5
      MECH      114.0      158.0      NaN 120.0

🔴 Section E: Advanced Level (For High Performers)

2️⃣1️⃣ Rank students based on marks (highest marks = Rank 1).

In [23]:
%sql
SELECT *, RANK() OVER (ORDER BY marks DESC) as rank FROM Students WHERE marks IS NOT NULL;

 student_id student_name department      city  marks  attendance  rank
        106        Priya         IT Hyderabad    190          97     1
        114        Kavya         CS      Pune    185          96     2
        120      Keerthi        ECE   Chennai    182          99     3
        101        Rahul         CS Hyderabad    178          95     4
        110        Pooja         IT      Pune    175          92     5
        115        Manoj         IT   Chennai    170          94     6
        102       Anjali         IT Bangalore    165          88     7
        111       Suresh         CS   Chennai    162          87     8
        117       Nikhil       MECH Bangalore    158          86     9
        108         Neha        ECE   Chennai    155          89    10
        103        Kiran         CS   Chennai    150          91    11
        118       Swathi         CS Hyderabad    148          88    12
        112        Deepa        ECE Bangalore    145          90    13
        104        Sneha        ECE Hyderabad    140          82    14
        113         Ajay       MECH Hyderabad    130          73    15
        105        Arjun       MECH      Pune    120          78    16
        119       Harsha         IT      Pune    110          72    17
        109        Rohit       MECH Hyderabad     98          65    18

2️⃣2️⃣ Find students whose marks are above the overall average marks.

In [24]:
%sql
SELECT * FROM Students WHERE marks > (SELECT AVG(marks) FROM Students);

 student_id student_name department      city  marks  attendance
        101        Rahul         CS Hyderabad    178          95
        102       Anjali         IT Bangalore    165          88
        106        Priya         IT Hyderabad    190          97
        108         Neha        ECE   Chennai    155          89
        110        Pooja         IT      Pune    175          92
        111       Suresh         CS   Chennai    162          87
        114        Kavya         CS      Pune    185          96
        115        Manoj         IT   Chennai    170          94
        117       Nikhil       MECH Bangalore    158          86
        120      Keerthi        ECE   Chennai    182          99

2️⃣3️⃣ Standardize the marks column using Min-Max Scaling.

In [25]:
%sql
WITH MinMax AS (SELECT MIN(marks) as min_m, MAX(marks) as max_m FROM Students)
SELECT *, (marks - min_m) / (max_m - min_m) as scaled_marks
FROM Students, MinMax;

 student_id student_name department      city  marks  attendance  min_m  max_m  scaled_marks
        101        Rahul         CS Hyderabad  178.0          95     98    190           0.0
        102       Anjali         IT Bangalore  165.0          88     98    190           0.0
        103        Kiran         CS   Chennai  150.0          91     98    190           0.0
        104        Sneha        ECE Hyderabad  140.0          82     98    190           0.0
        105        Arjun       MECH      Pune  120.0          78     98    190           0.0
        106        Priya         IT Hyderabad  190.0          97     98    190           1.0
        107       Vikram         CS Bangalore    NaN          84     98    190           NaN
        108         Neha        ECE   Chennai  155.0          89     98    190           0.0
        109        Rohit       MECH Hyderabad   98.0          65     98    190           0.0
        110        Pooja         IT      Pune  175.0          92     98    190           0.0
        111       Suresh         CS   Chennai  162.0          87     98    190           0.0
        112        Deepa        ECE Bangalore  145.0          90     98    190           0.0
        113         Ajay       MECH Hyderabad  130.0          73     98    190           0.0
        114        Kavya         CS      Pune  185.0          96     98    190           0.0
        115        Manoj         IT   Chennai  170.0          94     98    190           0.0
        116        Divya        ECE Hyderabad    NaN          80     98    190           NaN
        117       Nikhil       MECH Bangalore  158.0          86     98    190           0.0
        118       Swathi         CS Hyderabad  148.0          88     98    190           0.0
        119       Harsha         IT      Pune  110.0          72     98    190           0.0
        120      Keerthi        ECE   Chennai  182.0          99     98    190           0.0

2️⃣4️⃣ Categorize attendance into:
• Excellent (≥ 90)
• Good (75-89)
• Average (< 75)

In [26]:
%sql
SELECT *,
  CASE 
    WHEN attendance >= 90 THEN 'Excellent'
    WHEN attendance >= 75 THEN 'Good'
    ELSE 'Average'
  END as attendance_category
FROM Students;

 student_id student_name department      city  marks  attendance attendance_category
        101        Rahul         CS Hyderabad  178.0          95           Excellent
        102       Anjali         IT Bangalore  165.0          88                Good
        103        Kiran         CS   Chennai  150.0          91           Excellent
        104        Sneha        ECE Hyderabad  140.0          82                Good
        105        Arjun       MECH      Pune  120.0          78                Good
        106        Priya         IT Hyderabad  190.0          97           Excellent
        107       Vikram         CS Bangalore    NaN          84                Good
        108         Neha        ECE   Chennai  155.0          89                Good
        109        Rohit       MECH Hyderabad   98.0          65             Average
        110        Pooja         IT      Pune  175.0          92           Excellent
        111       Suresh         CS   Chennai  162.0          87                Good
        112        Deepa        ECE Bangalore  145.0          90           Excellent
        113         Ajay       MECH Hyderabad  130.0          73             Average
        114        Kavya         CS      Pune  185.0          96           Excellent
        115        Manoj         IT   Chennai  170.0          94           Excellent
        116        Divya        ECE Hyderabad    NaN          80                Good
        117       Nikhil       MECH Bangalore  158.0          86                Good
        118       Swathi         CS Hyderabad  148.0          88                Good
        119       Harsha         IT      Pune  110.0          72             Average
        120      Keerthi        ECE   Chennai  182.0          99           Excellent